# VoteFromServer Config File
# Make an Serverlistmc Accont Here: http://serverlistmc.tk
Server_Name: ''
Server_ip: ''
Server_Port: ''

# Find the Server ID by register your server here: http://serverlistmc.tk/add
# This will automatic make an ShortURL (listmc.tk/?s={your ID})
Serverlistmc_Server_ID: ''

# This is optional...
# You will need to have http:// in the url
# You can also use http://goo.gl/ to get Shorter URL
Planetminecraft_URL: ''
Minestatus_URL: ''
Minecraft-server-list_URL: ''
Minecraftservers.org_URL: ''
custom1_name: ''
custom1_URL: ''
custom2_name: ''
custom2_URL: ''
custom3_name: ''
custom3_URL: ''

# Setings
# %vote_url€ = Vote site url
# %vote_name% = Vote site Name
#
Header: 'You can vote here:'
Under_header: '%vote_name%'
Info_under: 'Do /vote (Vote site)'
Vote_page_header: 'Click At the URL to vote'
Vote_page_URL: '%vote_url%'
Cannot_find_vote_url: 'We cannot find that Vote URL, Please Try /vote'